prometheus_version: "2.53.3"
# prometheus_storage_retention: "30d"

# # Available since Prometheus 2.7.0
# # [EXPERIMENTAL] Maximum number of bytes that can be stored for blocks. Units
# # supported: KB, MB, GB, TB, PB.
# prometheus_storage_retention_size: "0"

# prometheus_agent_mode: false

# prometheus_global:
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   evaluation_interval: 15s
