---
  - name: Leggi il secret da Vault KV2 per zabbix_server
    set_fact:
     zabbix_server_secrets: "{{ 
      lookup('community.hashi_vault.vault_kv2_get', 
      'zabbix_server', 
      **vault_opts) 
      }}"

  - name: Estrai il username e password e memorizzali in variabili distinte
    set_fact:
     zabbix_dbname: "{{ zabbix_server_secrets.data.data.dbname }}"
     zabbix_dbuser: "{{ zabbix_server_secrets.data.data.dbuser }}"
     zabbix_password: "{{ zabbix_server_secrets.data.data.dbpassword }}"
  
  - name: Leggi un secret da Vault KV2
    set_fact:
     zabbix_agent_pg_user: "{{ lookup('community.hashi_vault.vault_kv2_get', 'zabbix_agent_pg_user',  **vault_opts) }}"

  - name: Estrai il username e password e memorizzali in variabili distinte
    set_fact:
     zabbix_agent_pg_username: "{{ zabbix_agent_pg_user.data.data.username }}"
     zabbix_agent_pg_password: "{{ zabbix_agent_pg_user.data.data.password }}"

  
  - name: Ensure ACL package is installed
    package:
       name: acl
       state: present

