---
    - name: Ensure firewalld is installed
      package:
        name: firewalld
        state: present
      tags: firewall, security

    - name: Ensure firewalld is started and enabled
      service:
        name: firewalld
        state: started
        enabled: yes
      tags: firewall, security

    - name: Ensure firewall zone is active
      ansible.builtin.firewalld:
        zone: "{{ firewall_zone }}"
        state: enabled
        permanent: yes
      when: firewall_zone != 'default'
      tags: firewall, security

    - name: Abilita le porte necessarie nel firewall  
      ansible.builtin.firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
        zone: "{{ firewall_zone }}"
        immediate: yes
      loop: "{{ firewall_ports }}"
      notify: reload Firewall
      tags: firewall, security
